name = "qs"
version = "0.6.0"

description = "Parse and encode URL query strings"
licences = ["MIT"]
repository = { type = "github", user = "sporto", repo = "gleam-qs" }

[dependencies]
gleam_stdlib = "~> 0.38"

[dev-dependencies]
gleeunit = "~> 1.0"
