name: test

on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Earthly
        uses: earthly/actions-setup@v1
        with:
          version: v0.8.0

      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: earthly --ci +all
